### ISSUE TITLE
"unknown command" errors

### ISSUE THREAD

**Issue by tlossen** [bogdanovich/siberite-ruby#5]
when talking to siberite [from two concurrent threads](https://gist.github.com/tlossen/2b2a11cec79e395fdc26d933d69fc7c4), i see lots of errors in the server log:

```
2017/01/23 10:49:55 [::1]:55272 ERROR Unknown command
2017/01/23 10:49:55 [::1]:55274 ERROR Unknown command
2017/01/23 10:49:55 [::1]:55275 ERROR Unknown command
2017/01/23 10:49:55 [::1]:55276 ERROR Unknown command
2017/01/23 10:49:55 [::1]:55282 ERROR Unknown command
2017/01/23 10:49:55 [::1]:55287 ERROR Unknown command
2017/01/23 10:49:55 [::1]:55294 ERROR Unknown command
```

(i think this only happens when i configure two siberite servers?)

**Comment by bogdanovich** [comment]
Root cause: memcached gem (used by siberite-ruby) is sending 'quit' command on disconnect.
Added support for 'quit' command to siberite: https://github.com/bogdanovich/siberite/pull/37

Should work fine now.

**Comment by tlossen** [comment]
cool!
